# This is a basic workflow that is manually triggered

on: [push]
name: Azure ARM
jobs:
  deploy-infrustructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy infrustructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: subscription
        region: australiasoutheast
        template: ./main.bicep
        failOnStdErr: false

  # build-functions:
  # TODO: build functions binaries

  # deploy-functions:
  # TODO: deploy function binaries